# Generated by Django 5.0.6 on 2024-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
