# Generated by Django 5.0.6 on 2024-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0004_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
